# Generated by Django 3.2.14 on 2023-10-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_assignment_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_assignment_usage_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_detector_usage_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lifetime_assignment_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lifetime_detector_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_assignment_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_detector_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_assignments_created',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
