# Generated by Django 3.2.14 on 2023-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20230831_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
