# Generated by Django 3.2.14 on 2023-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_criteria',
            field=models.TextField(null=True),
        ),
    ]
