# Generated by Django 3.2.14 on 2023-11-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignment_assignment_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.IntegerField(null=True),
        ),
    ]
