# Generated by Django 3.2.14 on 2024-01-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_assignment_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='has_ai_component',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='is_collaborative',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='learning_objectives',
        ),
    ]
