# Generated by Django 3.2.14 on 2024-01-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20240114_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='percent_of_cheating_students',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
