# Generated by Django 3.2.14 on 2023-04-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_auto_20230219_0230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
